```{r, include=FALSE}
## Set up the scipt environment defaults.
knitr::opts_chunk$set(echo = FALSE, cache=FALSE, warning = FALSE, message = FALSE, results = 'show' )
```

```{r}
## Set Month parameters 
# monthName <- character()
mName <- "November"
filePrefix <- "2111"

```



```{r, results='hide'}
## Set up:
### libraries
libs <- c("tidyverse", "lubridate", "knitr", "kableExtra")
libs <- append(libs,(c("mindr")))
lapply(libs, library, character.only = TRUE)  # load the required packages


### Functions and time stamps
ts <- stamp("Jan. 1 -- Monday") ## How dates will be displayed in document

add_consulting <- function(Date, Client, Project, Hours, Rate, Kms, Comment){
  add_row(Consulting, Date = Date, Client = Client, Project = Project,
          Hours = Hours, Rate = Rate, Kms = Kms, Comment = Comment)
}

### Data set up
#### Personal time tracking
myTime <- tibble(Date = character(), HoursWorked = numeric(), PersonalKMs = numeric(), ChargeKMs = numeric(), BankedTime = numeric())

#### Consulting table
Consulting <- tibble(Date = character(), Client = character(), Project = character(), Hours = numeric(), Rate = factor(), Kms = numeric(), Comment = character())
levels(Consulting$Rate) <- c("RPF", "Student", "Other")
```


# `r mName`

```{r}
#Carry over time from previous
CarryOver <- -0.0001
```
Note that `r CarryOver` hours of banked time have been carried over from last month.

<!-- NEW DAY ESSENTIALS ----------------------------------------> 

------------------

## May 3 -- Monday
  
```{r}
##NEW DAY ----------------------------------------------------
# items for time tracking
Date <- "2021-04-03" ## Type in this format!
HoursWorked  <-  8.0
BankedTime   <-  0.0
Personal_Kms <-  0.0
Charge_KMs   <-  0.0

myTime <- add_row(myTime, Date = Date, HoursWorked = HoursWorked, 
                  BankedTime = BankedTime, PersonalKMs = Personal_Kms, 
                  ChargeKMs = Charge_KMs)

```
<span style = "font-size: 10pt">
_Time worked: `r HoursWorked`; Personal use of ALRF vehicle: `r Personal_Kms`kms._
<!-- _Charging `r Charge_KMs`kms for use of personal vehicle._  -->
</span>
<!-- #dfdfdf for normal days.  #00edff (lt. blue) for home days--> 
<div style="background-color: #dfdfdf; border: 1px solid #111; border-radius:10px; padding: 5px" >


  
</div>


```{r}
# Consulting <- add_consulting(Date, "MSC", "paper1", 4, "RPF", 0, "NA")
```

<!-- END Day Essentials ---------------------------------------->




<!-- Below -- prep month summary info -->

------------------

\newpage
## Month Summary -- `r mName` 

_Banked time includes a carry over of `r CarryOver` hours from the previous month_



Raw data has been exported to:
  
```{r, echo=FALSE, results='show'}
dataexport <- "./dataexport"
write_csv(myTime, paste0(dataexport, "/myTime/",filePrefix, "_Mytime.csv"))
write_csv(Consulting, paste0(dataexport, "/Consulting/", filePrefix, "_Consulting.csv"))

files <- list.files(path = dataexport, full.names = TRUE, recursive = TRUE )
files
```





### My Time and ALRF vehicle use tracking {-}

```{r}
# myTime <- myTime %>% mutate(BankedTime = HoursWorked - 8)
myTimeSummary <- myTime %>% summarise(`Days Worked` = nrow(.),
                                      `Total Hours` = sum(HoursWorked),
                                      `Banked Time` = sum(BankedTime),
                                      `Vehicle Use` = sum(PersonalKMs),
                                      `Charge Kms`   = sum(ChargeKMs, na.rm = TRUE)) %>%
  mutate(`Banked Time` = `Banked Time` + CarryOver)

kable(myTimeSummary, caption = "My Time and ALRF vehicle use tracking",
      format = "markdown")
```





### Consulting time {-}

```{r}
kable(Consulting %>% group_by(Client, Project, Rate) %>%
        summarise(Hours = sum(Hours),
                  Kms   = sum(Kms)),
      format = "markdown",
      caption = "Consulting Time")
```


\newpage

### Consulting time (detailed) {-}

<!-- _pdf version only -- or see [exported data](#export03) _ -->
  
  
  
```{r}
kable(Consulting, caption = "Consulting time (detailed)", format = "markdown")
  # if (knitr::is_latex_output() == TRUE) {
  #   kable(Consulting, caption = "Consulting time (detailed)",
  #         format = "latex") %>% 
  #         kableExtra::kable_styling(latex_options = c("striped"),
  #                 full_width = F) %>% 
  #     kableExtra::column_spec(7, width = "30cm")
  # } else {
  #   kable(Consulting, caption = "Consulting time (detailed)",
  #         format = "html") %>% 
  #         kableExtra::kable_styling(bootstrap_options = "striped",
  #                 full_width = F) %>%
  #     kableExtra::column_spec(7, width = "30em")
  # }
  
```
  
  
  