<!-- NEW DAY ESSENTIALS ----------------------------------------> 

------------------

## Dec 3  -- Wednesday
  
```{r}
##NEW DAY ----------------------------------------------------
# items for time tracking
Date <- "2021-12-03" ## Type in this format!
HoursWorked  <-  8.0
BankedTime   <-  0.0
Personal_Kms <-  0.0
Charge_KMs   <-  0.0

myTime <- add_row(myTime, Date = Date, HoursWorked = HoursWorked, 
                  BankedTime = BankedTime, PersonalKMs = Personal_Kms, 
                  ChargeKMs = Charge_KMs)

```
<span style = "font-size: 10pt">
_Time worked: `r HoursWorked`; Personal use of ALRF vehicle: `r Personal_Kms`kms._
<!-- _Charging `r Charge_KMs`kms for use of personal vehicle._  -->
</span>
<!-- #dfdfdf for normal days.  #00edff (lt. blue) for home days--> 
<div style="background-color: #dfdfdf; border: 1px solid #111; border-radius:10px; padding: 5px" >


</div>


```{r}
# Consulting <- add_consulting(Date, "PEM", "meeting", 2, "RPF", 0, "meeting -- Pam and Gen provide an update.")
```

<!-- END Day Essentials ---------------------------------------->

